<?php

namespace Tiash\LaravelBkash\Exceptions;

class ErrorCodeMap
{
    private const MAP = [
        // Auth / Token
        2001 => 'Invalid App Key',
        2002 => 'Invalid Payment ID',
        2003 => 'Process failed',
        2004 => 'Invalid firstPaymentDate',
        2005 => 'Invalid frequency',
        2006 => 'Invalid amount',
        2007 => 'Invalid currency',
        2008 => 'Invalid intent',
        2009 => 'Invalid Wallet',
        2010 => 'Invalid OTP',
        2011 => 'Invalid PIN',
        2012 => 'Invalid Receiver MSISDN',
        2013 => 'Resend Limit Exceeded',
        2014 => 'Wrong PIN',
        2015 => 'Wrong PIN count exceeded',
        2016 => 'Wrong verification code',
        2017 => 'Wrong verification limit exceeded',
        2018 => 'OTP verification time expired',
        2019 => 'PIN verification time expired',
        2020 => 'Exception Occurred',
        2021 => 'Invalid Mandate ID',
        2022 => 'The mandate does not exist',
        2023 => 'Insufficient Balance',
        2024 => 'Exception occurred',
        2025 => 'Invalid request body',
        2026 => 'The reversal amount cannot be greater than the original transaction amount',
        2027 => 'The mandate corresponding to the payer reference number already exists and cannot be created again',
        2028 => 'Reverse failed because the transaction serial number does not exist',
        2029 => 'Duplicate for all transactions',
        2030 => 'Invalid mandate request type',
        2031 => 'Invalid merchant invoice number',
        2032 => 'Invalid transfer type',
        2033 => 'Transaction not found',
        2034 => 'The transaction cannot be reversed because the original transaction has been reversed',
        2035 => 'Reverse failed because the initiator has no permission to reverse the transaction',
        2036 => 'The direct debit mandate is not in Active state',
        2037 => 'The account of the debit party is in a state which prohibits execution of this transaction',
        2038 => 'Debit party identity tag prohibits execution of this transaction',
        2039 => 'The account of the credit party is in a state which prohibits execution of this transaction',
        2040 => 'Credit party identity tag prohibits execution of this transaction',
        2041 => 'Credit party identity is in a state which does not support the current service',
        2042 => 'Reverse failed because the initiator has no permission to reverse the transaction',
        2043 => 'The security credential of the subscriber is incorrect',
        2044 => 'Identity has not subscribed to a product that contains the expected service or the identity is not in Active status',
        2045 => 'The MSISDN of the customer does not exist',
        2046 => 'Identity has not subscribed to a product that contains requested service',
        2047 => 'TLV Data Format Error',
        2048 => 'Invalid Payer Reference',
        2049 => 'Invalid Merchant Callback URL',
        2050 => 'Agreement already exists between payer and merchant',
        2051 => 'Invalid Agreement ID',
        2052 => 'Agreement is in incomplete state',
        2053 => 'Agreement has already been cancelled',
        2054 => 'Agreement execution pre-requisite hasn\'t been met',
        2055 => 'Invalid Agreement State',
        2056 => 'Agreement cannot be cancelled',
        2057 => 'Agreement is already executed',
        2058 => 'Agreement is expired',
        2059 => 'Agreement is not found',
        2060 => 'Customer wallet is blocked',
        2061 => 'Customer wallet is not registered',
        2062 => 'Customer wallet is not active',
        2063 => 'Customer KYC not completed',
        2064 => 'Customer limit exceeded',
        2065 => 'Merchant wallet is blocked',
        2066 => 'Merchant wallet is not registered',
        2067 => 'Merchant wallet is not active',
        2068 => 'Merchant KYC not completed',
        2069 => 'Merchant limit exceeded',
        2070 => 'Invalid token',
        2071 => 'Refund after X days not allowed',
        2072 => 'Refund amount not valid',
        2073 => 'Invalid SKU',
        2074 => 'The transaction cannot be reversed',
        2075 => 'SKU Character Limit Exceeded',
        2076 => 'Reason Character Limit Exceeded',
        2077 => 'Invalid TrxID',
        2078 => 'Invalid Reason',
        2079 => 'Invalid app Token',
        2080 => 'The identity is not permitted to initiate this transaction',
        2081 => 'The identity of the debit or credit party is in a state which prohibits the execution of this transaction',
        2082 => 'The merchant is not permitted to initiate this transaction',
        2083 => 'Transaction amount exceeds limit',
        2084 => 'Daily transaction limit exceeded',
        2085 => 'Monthly transaction limit exceeded',
        2086 => 'Invalid payout ID',
        2087 => 'Payout already processed',
        2088 => 'Payout expired',
        2089 => 'Invalid receiver MSISDN for payout',
        2090 => 'Payout amount below minimum',
        2091 => 'Payout amount above maximum',
        2092 => 'Invalid payout reference',
        2093 => 'Duplicate payout reference',
        2094 => 'Insufficient merchant balance for payout',
        2095 => 'Payout fee calculation failed',
        2096 => 'Invalid payout type',
        2097 => 'Receiver not eligible for payout',
        2098 => 'Sender not eligible for payout',
        2099 => 'Payout transaction type mismatch',
        2100 => 'System maintenance',
        2101 => 'Service temporarily unavailable',
        2102 => 'Database connection failed',
        2103 => 'External service timeout',
        2104 => 'Rate limit exceeded',
        2105 => 'IP not whitelisted',
        2106 => 'Invalid API version',
        2107 => 'Missing required header',
        2108 => 'Invalid content type',
        2109 => 'Request body too large',
        2110 => 'Invalid JSON format',
        2111 => 'Missing required field',
        2112 => 'Field value too long',
        2113 => 'Invalid character in field',
        2114 => 'Duplicate request',
        2115 => 'Idempotency key expired',
        2116 => 'Idempotency key conflict',
        2117 => 'Webhook signature invalid',
        2118 => 'Webhook certificate untrusted',
        2119 => 'Webhook message ID duplicate',
        2120 => 'Webhook timestamp expired',
        2121 => 'Callback signature invalid',
        2122 => 'Callback URL not registered',
        2123 => 'Callback timeout',
        2124 => 'Payment session expired',
        2125 => 'Payment already executed',
        2126 => 'Payment not found',
        2127 => 'Transaction not yet completed',
        2128 => 'Agreement not found',
        2129 => 'Agreement expired',
        2130 => 'Agreement cancelled',
        2131 => 'Agreement not active',
        2132 => 'Payer reference mismatch',
        2133 => 'Merchant invoice number duplicate',
        2134 => 'Amount format invalid',
        2135 => 'Currency not supported',
        2136 => 'Intent not supported',
        2137 => 'Mode not supported',
        2138 => 'Invalid merchant association info',
        2139 => 'Payout ID not found',
        2140 => 'Payout status not available',
        2141 => 'B2B payout not allowed for this merchant',
        2142 => 'B2B receiver not a merchant',
        2143 => 'B2B amount exceeds limit',
        2144 => 'B2B daily limit exceeded',
        2145 => 'B2B monthly limit exceeded',
        2146 => 'Initiate payout required before B2B disbursement',
        2147 => 'Payout ID expired',
        2148 => 'Invalid payout status for disbursement',
        2149 => 'Payout already queried',
        2150 => 'Internal system error',
    ];

    public static function getMessage(int|string $code): string
    {
        $code = (int) $code;
        return self::MAP[$code] ?? "Unknown error code: {$code}";
    }

    public static function has(int|string $code): bool
    {
        return isset(self::MAP[(int) $code]);
    }

    public static function all(): array
    {
        return self::MAP;
    }
}